---
- name: Configure MaxAuthTries on SSH server
  hosts: all
  tasks:
    - name: Set MaxAuthTries in sshd_config
      replace:
        path: /etc/ssh/sshd_config
        regexp: '^#?MaxAuthTries\s+\w+'
        replace: 'MaxAuthTries 3 '
        backup: yes
      notify: Restart SSH Service

  handlers:
    - name: Restart SSH Service
      service:
        name: sshd
        state: restarted

