---
- name: Disable Packet Forwarding on Red Hat 8.6
  hosts: all
  tasks:
    - name: Set net.ipv4.ip_forward to 0
      sysctl:
        name: net.ipv4.ip_forward
        value: 0
        state: present
      become: yes
    - name: Check current value of net.ipv4.ip_forward
      shell: sysctl -n net.ipv4.ip_forward
      register: ip_forward_result
      become: yes

    - name: Display ip_forward result
      debug:
       msg: "net.ipv4.ip_forward is set to {{ ip_forward_result.stdout }}"


