- hosts: all
  tasks:
    - name: Password Length must be at least 12 Characters
      replace:
            dest: /etc/security/pwquality.conf
            regexp: '^# minlen =\s+\w+'
            replace: "minlen = 12"
      become: yes
