---
- name: Configure Password Expiry Policy
  hosts: all
  tasks:
    - name: Update PAM configuration for password expiry "max days and Password should change every 90 Days"
      replace:
        path: /etc/login.defs
        regexp: '^PASS_MAX_DAYS\s+\d+'
        replace: 'PASS_MAX_DAYS   90'
      become: yes
    - name: Update PAM configuration for password expiry "min days and you can change the  Password after 5 days"
      replace:
        path: /etc/login.defs
        regexp: '^PASS_MIN_DAYS\s+\d+'
        replace: 'PASS_MIN_DAYS    5'
      become: yes
    - name: Update PAM configuration for password expiry "Number of days warning given before a password expires"
      replace:
        path: /etc/login.defs
        regexp: '^PASS_WARN_AGE\s+\d+'
        replace: 'PASS_WARN_AGE    14'
      become: yes
    - name: Update PAM configuration for password expiry "Number of days warning given before a password expires"
      replace:
        path: /etc/login.defs
        regexp: '^PASS_MIN_LEN\s+\d+'
        replace: 'PASS_MIN_LEN    12'
      become: yes





