- hosts: all
  tasks:
    - name: Password Complexity must be enabled and support alphanumeric "minclass The minimum number of required classes of characters for the new password (digits, uppercase, lowercase, others). Minclass=4"

      replace:
            dest: /etc/security/pwquality.conf
            regexp: '^# minclass =\s+\w+'
            replace: "minclass = 4"
    - name: Password Complexity must be enabled and support alphanumeric "the minimum number of characters that must be different from the old password"
      replace:
            dest: /etc/security/pwquality.conf
            regexp: '^# difok =\s+\w+'
            replace: "difok = 5"

    - name: Password Complexity must be enabled and support alphanumeric "This implies that the password should have at last a numeric character"
      replace:
            dest: /etc/security/pwquality.conf
            regexp: '^# dcredit =\s+\w+'
            replace: "dcredit = -1"

    - name: Password Complexity must be enabled and support alphanumeric "The option requires at least one uppercase character in the password"
      replace:
            dest: /etc/security/pwquality.conf
            regexp: '^# ucredit =\s+\w+'
            replace: "ucredit = -1"
    - name: Password Complexity must be enabled and support alphanumeric "The option requires at least one lowercase character in the password"
      replace:
            dest: /etc/security/pwquality.conf
            regexp: '^# lcredit =\s+\w+'
            replace: "lcredit = -1"

    - name: Password Complexity must be enabled and support alphanumeric "The option requires at least one special character included in the password"
      replace:
            dest: /etc/security/pwquality.conf
            regexp: '^# ocredit =\s+\w+'
            replace: "ocredit = -1"
 
