---
- name: Configure Password History on Linux
  hosts: all
  tasks:
    - name: Set Password History in PAM
      lineinfile:
        path: /etc/pam.d/password-auth
        line: "password required pam_pwhistory.so nullok  remember=4"
        insertafter: "# here are the per-package modules (the 'Primary' block)"
      become: yes
    - name: Set Password History in PAM
      lineinfile:
        path: /etc/pam.d/system-auth
        line: "password required pam_pwhistory.so nullok  remember=4"
        insertafter: "# here are the per-package modules (the 'Primary' block)"
      become: yes

