---
- name: Configure Account Lockout Policy
  hosts: all
  tasks:
    - name: Update PAM configuration for account lockout in system-auth
      lineinfile:
        path: /etc/pam.d/system-auth
        regexp: '^auth\s+required\s+pam_unix\.so'
        line: 'auth required pam_faillock.so preauth silent deny=6 unlock_time=1800 fail_interval=900'
        backup: yes
      become: yes

    - name: Update PAM configuration for account lockout in password-auth
      lineinfile:
        path: /etc/pam.d/password-auth
        regexp: '^auth\s+required\s+pam_unix\.so'
        line: 'auth required pam_faillock.so preauth silent deny=6 unlock_time=1800 fail_interval=900'
        backup: yes
      become: yes

